/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
//import GUI.Panel_KhachHang;
//import com.sun.org.apache.xml.internal.resolver.helpers.PublicId;
import javax.swing.ImageIcon;

/**
 *
 * @author Win 10
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Tour
     */
    public Frame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = screenSize.width - 948;
        int x1 = x / 2;
        this.setBounds(x1, 20, 948, 661);
        this.setResizable(false);
        this.setTitle("Quản Lý Bán Hàng");

        ImageAndIcons();
    }

    public void ImageAndIcons() {
        ImageIcon img = new ImageIcon("src/Images/bg.jpg");
        lbl_Image.setIcon(img);
        
        ImageIcon logo = new ImageIcon("src/Images/logo.png");
        lblLogo.setIcon(logo);

        ImageIcon icsp = new ImageIcon("src/Images/icon-sanpham.png");
        ImageIcon icdh = new ImageIcon("src/Images/icon-dathang.png");
        ImageIcon icnh = new ImageIcon("src/Images/icon-nhaphang.png");
        ImageIcon icbh = new ImageIcon("src/Images/icon-banhang.png");
        ImageIcon icpg = new ImageIcon("src/Images/icon-phieugiao.png");
        ImageIcon icdx = new ImageIcon("src/Images/icon-dangxuat.png");

        btnSanpham.setIcon(icsp);
        btnNhaphang.setIcon(icnh);
        btnBanhang.setIcon(icbh);
        btnDathang.setIcon(icdh);
        btnPhieugiao.setIcon(icpg);
        btnDangXuat.setIcon(icdx);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBanhang = new javax.swing.JButton();
        btnSanpham = new javax.swing.JButton();
        btnPhieugiao = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnDathang = new javax.swing.JButton();
        btnNhaphang = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 166, 254));

        btnBanhang.setBackground(new java.awt.Color(204, 0, 204));
        btnBanhang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBanhang.setText("Bán hàng");
        btnBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhangActionPerformed(evt);
            }
        });

        btnSanpham.setBackground(new java.awt.Color(204, 0, 204));
        btnSanpham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSanpham.setText("Sản phẩm");
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });

        btnPhieugiao.setBackground(new java.awt.Color(204, 0, 204));
        btnPhieugiao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhieugiao.setText("Phiếu giao hàng");
        btnPhieugiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieugiaoActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(153, 153, 153));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 0, 51));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnDathang.setBackground(new java.awt.Color(204, 0, 204));
        btnDathang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDathang.setText("Đặt hàng");
        btnDathang.setToolTipText("");
        btnDathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDathangActionPerformed(evt);
            }
        });

        btnNhaphang.setBackground(new java.awt.Color(204, 0, 204));
        btnNhaphang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhaphang.setText("Nhập hàng");
        btnNhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaphangActionPerformed(evt);
            }
        });

        lblLogo.setBackground(new java.awt.Color(255, 51, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBanhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(btnPhieugiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDathang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDathang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPhieugiao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(786, 629));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Panel_SanPham pnSP = new Panel_SanPham();
    Panel_DatHang pnDH = new Panel_DatHang();
    Panel_NhapHang pnNH = new Panel_NhapHang();
    Panel_BanHang pnBH = new Panel_BanHang();
    Panel_PhieuGiao pnPG = new Panel_PhieuGiao();


    private void btnBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhangActionPerformed
//         TODO add your handling code here:
        if (evt.getSource() == btnBanhang) {
            jPanel3.removeAll();
            jPanel3.add(pnBH);
            jPanel3.repaint();
            pnBH.repaint();
            pnBH.revalidate();
            pnBH.setMakh();
            pnBH.setMasp();
            btnBanhang.setBackground(new java.awt.Color(0,206,209));
            btnDathang.setBackground(new java.awt.Color(204,0,204));
            btnNhaphang.setBackground(new java.awt.Color(204,0,204));
            btnSanpham.setBackground(new java.awt.Color(204,0,204));
            btnPhieugiao.setBackground(new java.awt.Color(204,0,204));
        }
    }//GEN-LAST:event_btnBanhangActionPerformed

    private void btnDathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDathangActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnDathang) {
            jPanel3.removeAll();
            jPanel3.add(pnDH);
            jPanel3.repaint();
            pnDH.revalidate();
            pnDH.repaint();
            btnBanhang.setBackground(new java.awt.Color(204,0,204));
            btnDathang.setBackground(new java.awt.Color(0,206,209));
            btnNhaphang.setBackground(new java.awt.Color(204,0,204));
            btnSanpham.setBackground(new java.awt.Color(204,0,204));
            btnPhieugiao.setBackground(new java.awt.Color(204,0,204));
        }
    }//GEN-LAST:event_btnDathangActionPerformed

    private void btnNhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaphangActionPerformed
        if (evt.getSource() == btnNhaphang) {
            jPanel3.removeAll();
            jPanel3.add(pnNH);
            jPanel3.repaint();
            pnNH.revalidate();
            pnNH.repaint();
            btnBanhang.setBackground(new java.awt.Color(204,0,204));
            btnDathang.setBackground(new java.awt.Color(204,0,204));
            btnNhaphang.setBackground(new java.awt.Color(0,206,209));
            btnSanpham.setBackground(new java.awt.Color(204,0,204));
            btnPhieugiao.setBackground(new java.awt.Color(204,0,204));
        }
    }//GEN-LAST:event_btnNhaphangActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        if (evt.getSource() == btnSanpham) {
            jPanel3.removeAll();
            jPanel3.add(pnSP);
            jPanel3.repaint();
            pnSP.revalidate();
            pnSP.repaint();
            btnBanhang.setBackground(new java.awt.Color(204,0,204));
            btnDathang.setBackground(new java.awt.Color(204,0,204));
            btnNhaphang.setBackground(new java.awt.Color(204,0,204));
            btnSanpham.setBackground(new java.awt.Color(0,206,209));
            btnPhieugiao.setBackground(new java.awt.Color(204,0,204));
        }
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void btnPhieugiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieugiaoActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnPhieugiao) {
            jPanel3.removeAll();
            jPanel3.add(pnPG);
            jPanel3.repaint();
            pnPG.revalidate();
            pnPG.repaint();
            new Panel_PhieuGiao().loadData();
            btnBanhang.setBackground(new java.awt.Color(204,0,204));
            btnDathang.setBackground(new java.awt.Color(204,0,204));
            btnNhaphang.setBackground(new java.awt.Color(204,0,204));
            btnSanpham.setBackground(new java.awt.Color(204,0,204));
            btnPhieugiao.setBackground(new java.awt.Color(0,206,209));
        }
    }//GEN-LAST:event_btnPhieugiaoActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnDangXuat) {
            this.setVisible(false);
           //new DangNhapFrm().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f = new Frame();
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanhang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDathang;
    private javax.swing.JButton btnNhaphang;
    private javax.swing.JButton btnPhieugiao;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbl_Image;
    // End of variables declaration//GEN-END:variables
}
