/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.BillDTO;
import DTO.ChiTietBillDTO;
import DTO.DatHangDTO;
import DTO.KhachHangDTO;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Win 10
 */
public class Panel_DatHang_XemChiTiet extends javax.swing.JFrame {

    public static int index_DatHang_XemChiTiet;
    public static ArrayList<DatHangDTO> datHangList = new ArrayList<>();
    int i = index_DatHang_XemChiTiet;
    int n;

    /**
     * Creates new form Panel_DatHang_XemChiTiet
     */
    public Panel_DatHang_XemChiTiet() {

        this.setResizable(false);

        this.setSize(new Dimension(741, 510));
        this.setLocationRelativeTo(null);
        initComponents();
        if (txtState.getText().equals("Đã duyệt")) {
            btnDuyet.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTruoc = new javax.swing.JButton();
        btnTiep = new javax.swing.JButton();
        lblAnhSP = new javax.swing.JLabel();
        btnDuyet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTen = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JLabel();
        txtSdt = new javax.swing.JLabel();
        txtMadon = new javax.swing.JLabel();
        txtMaSp = new javax.swing.JLabel();
        txtSl = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbDiscount = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(741, 510));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin đặt hàng");

        btnTruoc.setText("Về trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnTiep.setText("Kế tiếp");
        btnTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepActionPerformed(evt);
            }
        });

        btnDuyet.setText("Duyệt đơn");
        btnDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Tên khách hàng:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Địa chỉ:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Mã đơn:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Mã sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Số lượng:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Giá:");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTen.setText("jLabel9");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDiaChi.setText("jLabel10");

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSdt.setText("jLabel11");

        txtMadon.setBackground(new java.awt.Color(204, 255, 51));
        txtMadon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMadon.setForeground(new java.awt.Color(255, 51, 0));
        txtMadon.setText("jLabel12");

        txtMaSp.setBackground(new java.awt.Color(255, 102, 102));
        txtMaSp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaSp.setText("jLabel13");

        txtSl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSl.setText("jLabel14");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGia.setText("jLabel15");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Giảm giá:");

        cbDiscount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "50" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Trạng thái:");

        txtState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtState.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(btnDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSl)
                                    .addComponent(txtMaSp)
                                    .addComponent(txtMadon)
                                    .addComponent(txtSdt)
                                    .addComponent(txtDiaChi)
                                    .addComponent(cbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiaChi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSdt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMadon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaSp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtGia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtState))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepActionPerformed
        // TODO add your handling code here:
        i++;
        n = i + 1;
        DatHangDTO datHangDTO;
        if (i > datHangList.size() - 1) {
            i = 0;
        } else {
            datHangDTO = datHangList.get(i);
            KhachHangDTO kh = BLL.KhachHangBLL.getKhachHangByID(String.valueOf(datHangDTO.getCustomer_id()));
            txtTen.setText(kh.getCustomer_name());
            txtDiaChi.setText(kh.getCustomer_address());
            txtSdt.setText(kh.getCustomer_contact());
            txtMadon.setText(String.valueOf(datHangDTO.getCard_id()));
            txtMaSp.setText(String.valueOf(datHangDTO.getProduct_id()));
            txtSl.setText(String.valueOf(datHangDTO.getQuantity()));
            txtGia.setText(String.valueOf(datHangDTO.getPrice()));
            ImageIcon icon = new ImageIcon("src/image/" + datHangDTO.getImage());
            lblAnhSP.setIcon(icon);

            if (n > datHangList.size() - 1) {
                JOptionPane.showMessageDialog(null, "Đã hết đơn cần duyệt");
                cbDiscount.setSelectedIndex(0);
                n = datHangList.size() - 1;
            } else {
                DatHangDTO next = datHangList.get(n);
                if (datHangDTO.getCard_id() == next.getCard_id()) {
                    cbDiscount.setSelectedIndex(0);
                }
            }

//                    int p = i + 1;
            int p = i - 1;
            if (datHangList.get(p).getCard_id() < datHangList.get(i).getCard_id()) {
                btnDuyet.setEnabled(false);
            }
//                if (datHangList.get(p).getCard_id() > datHangList.get(p - 1).getCard_id()) {
//                    btnDuyet.setEnabled(false);
//                }

        }

    }//GEN-LAST:event_btnTiepActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        i--;
        n = i - 1;
        if (i < 0) {
            i = datHangList.size() - 1;
        } else {
            DatHangDTO datHangDTO = datHangList.get(i);
//            DatHangDTO a = new DatHangDTO(i, WIDTH, SOMEBITS, PROPERTIES, product_name, image, SOMEBITS, ERROR)
            KhachHangDTO kh = BLL.KhachHangBLL.getKhachHangByID(String.valueOf(datHangDTO.getCustomer_id()));
            txtTen.setText(kh.getCustomer_name());
            txtDiaChi.setText(kh.getCustomer_address());
            txtSdt.setText(kh.getCustomer_contact());
//            txtMadon.setText(String.valueOf(datHangDTO.getCard_id()));
            txtMadon.setText(String.valueOf(datHangDTO.getCard_id()));
            txtMaSp.setText(String.valueOf(datHangDTO.getProduct_id()));
            txtSl.setText(String.valueOf(datHangDTO.getQuantity()));
            txtGia.setText(String.valueOf(datHangDTO.getPrice()));
            ImageIcon icon = new ImageIcon("src/image/" + datHangDTO.getImage());
            lblAnhSP.setIcon(icon);

            if (n < 0) {
                JOptionPane.showMessageDialog(null, "Đã về đầu danh sách cần duyệt");
                cbDiscount.setSelectedIndex(0);
//                n = datHangList.size() + 1;
            } else {
                DatHangDTO next = datHangList.get(n);
                if (datHangDTO.getCard_id() == next.getCard_id()) {
                    Panel_NhapHang nhaphang = new Panel_NhapHang();
                    cbDiscount.setSelectedIndex(0);
                }
            }
            int p = i+1;
            if (datHangList.get(p).getCard_id() > datHangList.get(p - 1).getCard_id()) {
                btnDuyet.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetActionPerformed
        try {
            // TODO add your handling code here:
            cbDiscount.setSelectedIndex(0);
            int sl = Integer.parseInt(txtSl.getText());
            String MaSp = txtMaSp.getText();
            int sl_from_db = Integer.parseInt(BLL.SanPhamBLL.finQuantityByID(MaSp));

            if (sl > sl_from_db) {
                JOptionPane.showMessageDialog(null, "Sản phẩm " + txtMaSp.getName() + " có số lượng không đủ. Hãy nhập thêm hàng!");
            } else {
                ArrayList<DatHangDTO> cartList = new ArrayList<>();
                String id = txtMadon.getText();
                BLL.DatHangBLL.updateStateCart(id);
                DatHangDTO datHangDTO = datHangList.get(i);
                cartList = BLL.DatHangBLL.loadAmountCart(id);
                int price = 0;
                for (int a = 0; a < cartList.size(); a++) {
                    price = (int) (cartList.get(a).getPrice() * cartList.get(a).getQuantity()) + price;
                }
                int discount = cbDiscount.getSelectedIndex();
                price = price - (price * ((discount * 100) / 100));
                BillDTO bill = new BillDTO(cbDiscount.getSelectedIndex(), (int) price, datHangDTO.getCustomer_id());

                DAL.BillDAL.addBill(bill);
                ArrayList<BillDTO> loadDataBill = DAL.BillDAL.loadDataBill();
                for (int i = 0; i < cartList.size(); i++) {
                    int product_id = cartList.get(i).getProduct_id();
                    int qty = cartList.get(i).getQuantity();
                    int cost = (int) cartList.get(i).getPrice();
                    int bill_id = cartList.get(i).getCard_id();
                    ChiTietBillDTO chiTietBill = new ChiTietBillDTO(product_id, qty, cost, bill_id);
                    DAL.ChiTietBillDAL.addChiTietBill(chiTietBill);
                }
                JOptionPane.showMessageDialog(null, "Thêm hóa đơn thành công.");
//                for(int i = 0; i < cartList.size(); i++){
//                    int p = i + 1;
//                    if(cartList.get(i).getCard_id() < cartList.get(p).getCard_id()){
//                        btnDuyet.setEnabled(false);
//                    }
//                    if(cartList.get(i).getCard_id() > cartList.get(i-1).getCard_id()){
//                        btnDuyet.setEnabled(false);
//                    }
//                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Panel_DatHang_XemChiTiet.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnDuyetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_DatHang_XemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_DatHang_XemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_DatHang_XemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_DatHang_XemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_DatHang_XemChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnDuyet;
    private javax.swing.JButton btnTiep;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lblAnhSP;
    public static javax.swing.JLabel txtDiaChi;
    public static javax.swing.JLabel txtGia;
    public static javax.swing.JLabel txtMaSp;
    public static javax.swing.JLabel txtMadon;
    public static javax.swing.JLabel txtSdt;
    public static javax.swing.JLabel txtSl;
    public static javax.swing.JLabel txtState;
    public static javax.swing.JLabel txtTen;
    // End of variables declaration//GEN-END:variables
}
