/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.KhachHangBLL;
import BLL.PhieuGiaoHangBLL;
import static BLL.PhieuGiaoHangBLL.loadDataPhieuGiaoHang;
import DTO.KhachHangDTO;
import DTO.PhieuGiaoHangDTO;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.Phaser;
import javafx.scene.control.Cell;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Win 10
 */
public class Panel_PhieuGiao extends javax.swing.JPanel {

    public ArrayList<PhieuGiaoHangDTO> listphieugiaohang;
    public DefaultTableModel model;
    String item_combobox;
    public int index_tbl;

    ArrayList<KhachHangDTO> listkhachhang;

    public Panel_PhieuGiao() {
        initComponents();
        this.setBounds(0, 0, 786, 632);
        this.setBorder(BorderFactory.createLineBorder(Color.black));

        listphieugiaohang = new ArrayList<>();
        model = (DefaultTableModel) tblPhieugiaohang.getModel();

        listkhachhang = new ArrayList<>();

        loadDataCB(cbMakhachhang);
        loadData();
        Timkiem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieugiaohang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnInphieu = new javax.swing.JButton();
        cbMakhachhang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnXem = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(786, 629));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("PHIẾU GIAO HÀNG");

        tblPhieugiaohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu giao hàng", "Mã giỏ hàng", "Mã khách hàng", "Mã sản phẩm", "Tên sản phẩm", "Hình ảnh", "Số lượng", "Giá"
            }
        ));
        tblPhieugiaohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieugiaohangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieugiaohang);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Tìm Kiếm :");

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setText("Cập Nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnInphieu.setText("In Phiếu");
        btnInphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInphieuActionPerformed(evt);
            }
        });

        cbMakhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMakhachhangMouseClicked(evt);
            }
        });
        cbMakhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakhachhangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Mã Khách Hàng:");

        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(219, 219, 219))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnXem)
                                .addGap(18, 18, 18)
                                .addComponent(btnInphieu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnThem)
                .addGap(108, 108, 108)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(107, 107, 107)
                .addComponent(btnCapnhat)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMakhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnInphieu)
                            .addComponent(btnXem))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnCapnhat)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        new ThemPGH().setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        index_tbl = tblPhieugiaohang.getSelectedRow();
        SuaPGH s = new SuaPGH();
        s.setVisible(true);
        s.txtMaphieugiaohang.setText(model.getValueAt(index_tbl, 0).toString().trim());
        s.cbMagiohang.setSelectedItem(model.getValueAt(index_tbl, 1).toString().trim());
        s.cbMakhachhang.setSelectedItem(model.getValueAt(index_tbl, 2).toString().trim());
        s.cbMasanpham.setSelectedItem(model.getValueAt(index_tbl, 3).toString().trim());
        s.txtTensanpham.setText(model.getValueAt(index_tbl, 4).toString().trim());
        s.txtLinkhinhanh.setText(model.getValueAt(index_tbl, 5).toString().trim());
        s.txtSoluong.setText(model.getValueAt(index_tbl, 6).toString().trim());
        s.txtGia.setText(model.getValueAt(index_tbl, 7).toString().trim());
        s.loadAnh();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblPhieugiaohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieugiaohangMouseClicked

    }//GEN-LAST:event_tblPhieugiaohangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        index_tbl = tblPhieugiaohang.getSelectedRow();
        int data = Integer.parseInt(model.getValueAt(index_tbl, 0).toString().trim());
        if (index_tbl >= 0) {
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ???") == 0) {
                new PhieuGiaoHangBLL().removePhieuGiaoHang(data);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        loadData();
        tblPhieugiaohang.setColumnSelectionAllowed(false);
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnInphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInphieuActionPerformed
        try {
            String path = "C:\\Users\\DELL\\Desktop\\phieugiaohang.pdf";
            Document document = new Document();

            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();
            Paragraph preface = new Paragraph();
            preface.setAlignment(Element.ALIGN_CENTER);
            preface.add(new Phrase("PHIEU GIAO HANG \n\n",boldFont));
            document.add(preface);

            listkhachhang = new KhachHangBLL().getKhachHangToNameByID(item_combobox);

            String customer_name = listkhachhang.get(0).getCustomer_name();
            System.out.println(customer_name);
            Paragraph p_name_customer = new Paragraph(new Phrase("Ho ten khach hang:  " + customer_name));
            document.add(p_name_customer);

            String address = listkhachhang.get(0).getCustomer_address();
            String country = listkhachhang.get(0).getCustomer_country();
            String city = listkhachhang.get(0).getCustomer_city();
            Paragraph p_address = new Paragraph(new Phrase("DIA CHI:  " + address + " " + country + " " + city));
            document.add(p_address);

            Paragraph p_phone = new Paragraph(new Phrase("SO DIEN THOAI: ........................ \n \n "));
            document.add(p_phone);
            document.left(300);

            PdfPTable table = new PdfPTable(4);
            table.addCell("STT");
            table.addCell("Ten san pham");
            table.addCell("Don gia");
            table.addCell("So luong");

            for (int i = 0; i < tblPhieugiaohang.getRowCount(); i++) {

                String tensp = model.getValueAt(i, 4).toString();
                String dongia = model.getValueAt(i, 7).toString();
                String soluong = model.getValueAt(i, 6).toString();

                table.addCell(String.valueOf(i + 1));
                table.addCell(tensp);
                table.addCell(dongia);
                table.addCell(soluong);
            }
            document.add(table);

            Paragraph p_time = new Paragraph(30, "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + city + " Ngay " + "..." + " Thang " + "..." + " Nam " + "....");
            document.add(p_time);

            Paragraph preface5 = new Paragraph(30,"NGUOI GIAO HANG"+"\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"+"NGUOI NHAN HANG");
            document.add(preface5);
            

            Paragraph preface6 = new Paragraph(60, "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
                    + customer_name);
            document.add(preface6);

            JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công");
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnInphieuActionPerformed

    private void cbMakhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMakhachhangActionPerformed

    private void cbMakhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMakhachhangMouseClicked

    }//GEN-LAST:event_cbMakhachhangMouseClicked

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        item_combobox = cbMakhachhang.getSelectedItem().toString();
        listphieugiaohang = new PhieuGiaoHangBLL().loadDataPhieuGiaoHangByIdCus(item_combobox);
        model.setRowCount(0);
        for (PhieuGiaoHangDTO p : listphieugiaohang) {
            model.addRow(new Object[]{
                p.getId(), p.getCart_id(), p.getCustomer_id(), p.getProduct_id(), p.getProduct_name(), p.getImage(),
                p.getQuantity(), p.getPrice()
            });
        }

    }//GEN-LAST:event_btnXemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnInphieu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMakhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhieugiaohang;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        listphieugiaohang = new PhieuGiaoHangBLL().loadDataPhieuGiaoHang();
        model.setRowCount(0);
        for (PhieuGiaoHangDTO phieuGiaoHangDTO : listphieugiaohang) {
            model.addRow(new Object[]{
                phieuGiaoHangDTO.getId(), phieuGiaoHangDTO.getCart_id(), phieuGiaoHangDTO.getCustomer_id(), phieuGiaoHangDTO.getProduct_id(),
                phieuGiaoHangDTO.getProduct_name(), phieuGiaoHangDTO.getImage(), phieuGiaoHangDTO.getQuantity(), phieuGiaoHangDTO.getPrice()
            });
        }
    }

    private void Timkiem() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblPhieugiaohang.getModel());
        tblPhieugiaohang.setRowSorter(rowSorter);
        txtTimkiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                String text = txtTimkiem.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = txtTimkiem.getText();
                if (text.length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    private void loadDataCB(JComboBox<String> cbMakhachhang) {
        new PhieuGiaoHangBLL().loadCbCustomerId(cbMakhachhang);
    }
}
