/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.PhieuGiaoHangBLL;
import BLL.SanPhamBLL;
import DTO.PhieuGiaoHangDTO;
import DTO.SanPhamDTO;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class SuaPGH extends javax.swing.JFrame {

    /**
     * Creates new form SuaPGH
     */
    ArrayList<SanPhamDTO> listsp = new ArrayList<>();

    public SuaPGH() {
        initComponents();
        this.setLocationRelativeTo(null);

        txtMaphieugiaohang.setEnabled(false);
        loadCbCart(cbMagiohang);
        loadCbCustomer(cbMakhachhang);
        loadCbProduct(cbMasanpham);

        loadAnh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaphieugiaohang = new javax.swing.JTextField();
        cbMagiohang = new javax.swing.JComboBox<>();
        cbMakhachhang = new javax.swing.JComboBox<>();
        cbMasanpham = new javax.swing.JComboBox<>();
        txtTensanpham = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtLinkhinhanh = new javax.swing.JTextField();
        lbHinhanh = new javax.swing.JLabel();
        btnChonanh = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sửa Phiếu Giao Hàng");

        jLabel2.setText("Mã phiếu giao hàng:");

        jLabel3.setText("Mã giỏ hàng:");

        jLabel4.setText("Mã khách hàng:");

        jLabel5.setText("Mã sản phẩm:");

        jLabel6.setText("Tên sản phẩm:");

        jLabel7.setText("Số lượng:");

        jLabel8.setText("Giá:");

        jLabel9.setText("Hình ảnh:");

        cbMasanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMasanphamActionPerformed(evt);
            }
        });

        lbHinhanh.setText("jLabel10");

        btnChonanh.setText("Chọn");
        btnChonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonanhActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLammoi.setText("Làm Mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnLammoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnThoat))
                                    .addComponent(txtMaphieugiaohang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMagiohang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMakhachhang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMasanpham, javax.swing.GroupLayout.Alignment.LEADING, 0, 192, Short.MAX_VALUE)
                                    .addComponent(txtTensanpham, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLinkhinhanh, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonanh))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnSua)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaphieugiaohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbMagiohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbMakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLinkhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonanh)))
                .addGap(18, 18, 18)
                .addComponent(lbHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnLammoi)
                    .addComponent(btnThoat))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void Reset() {
        txtMaphieugiaohang.setText("");
        cbMagiohang.setSelectedIndex(0);
        cbMakhachhang.setSelectedIndex(0);
        cbMasanpham.setSelectedIndex(0);
        txtTensanpham.setText("");
        txtLinkhinhanh.setText("");
        txtSoluong.setText("");
        txtGia.setText("");
        lbHinhanh.setIcon(null);
    }
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        Reset();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        PhieuGiaoHangDTO pgh = new PhieuGiaoHangDTO();

        String pro_name = txtTensanpham.getText();
        String ImageString = txtLinkhinhanh.getText();
        String quantity = txtSoluong.getText();
        String price = txtGia.getText();
        boolean isOK = true;

        if (pro_name.length() == 0) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống");
            isOK = false;
        } else if (ImageString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Link hình ảnh không được để trống");
            isOK = false;
        } else if (quantity.length() == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống");
            isOK = false;
        } else if (price.length() == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống");
            isOK = false;
        }

        if (price.length() > 0 && !price.matches("\\d*")) {
            JOptionPane.showMessageDialog(this, "Giá nhập là số");
            isOK = false;
        } else {
            isOK = true;
        }
        if (quantity.length() > 0 && !quantity.matches("\\d*")) {
            JOptionPane.showMessageDialog(this, "Số lượng nhập là số");
            isOK = false;
        } else {
            isOK = true;
        }

        pgh.setId(Integer.parseInt(txtMaphieugiaohang.getText()));
        pgh.setCart_id(Integer.parseInt(cbMagiohang.getSelectedItem().toString()));
        pgh.setCustomer_id(Integer.parseInt(cbMakhachhang.getSelectedItem().toString()));
        pgh.setProduct_id(Integer.parseInt(cbMasanpham.getSelectedItem().toString()));
        pgh.setProduct_name(pro_name);
        pgh.setImage(txtLinkhinhanh.getText());
        pgh.setQuantity(Integer.parseInt(txtSoluong.getText()));
        pgh.setPrice(Integer.parseInt(txtGia.getText()));

        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không ???") == 0) {
            if (new PhieuGiaoHangBLL().editPhieuGiaoHang(pgh) == true) {
                JOptionPane.showConfirmDialog(this, "Sửa thành công");
                this.dispose();
                new Panel_PhieuGiao().loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnChonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonanhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("F:\\xampp\\htdocs\\hangdientu\\image"));
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image File (*.jpg)";
            }
        });

        if (chooser.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        try {
            File selectedFile = new File(chooser.getSelectedFile().getAbsolutePath());
            Image i = ImageIO.read(selectedFile);
            //Định dạng file và chuyển vào thư mục sach
            File tempfile = new File(selectedFile.getPath()); // tạo file tạm
            String tenanh = selectedFile.getName(); // lấy tên ảnh
            txtLinkhinhanh.setText(tenanh);
            lbHinhanh.setIcon(new ImageIcon(i.getScaledInstance(lbHinhanh.getWidth(), lbHinhanh.getHeight(), java.awt.Image.SCALE_SMOOTH)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChonanhActionPerformed

    private void cbMasanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMasanphamActionPerformed
        String product_id = cbMasanpham.getSelectedItem().toString();
        listsp = new SanPhamBLL().loadNameSPById(product_id);
        String product_name = listsp.get(0).getTenSP();
        txtTensanpham.setText(product_name);
    }//GEN-LAST:event_cbMasanphamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaPGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaPGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaPGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaPGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaPGH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonanh;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThoat;
    public javax.swing.JComboBox<String> cbMagiohang;
    public javax.swing.JComboBox<String> cbMakhachhang;
    public javax.swing.JComboBox<String> cbMasanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbHinhanh;
    public javax.swing.JTextField txtGia;
    public javax.swing.JTextField txtLinkhinhanh;
    public javax.swing.JTextField txtMaphieugiaohang;
    public javax.swing.JTextField txtSoluong;
    public javax.swing.JTextField txtTensanpham;
    // End of variables declaration//GEN-END:variables

    public void loadAnh() {
        String anh = txtLinkhinhanh.getText();
        ImageIcon icon = new ImageIcon(new ImageIcon("F:\\xampp\\htdocs\\hangdientu\\image\\" + anh).getImage().getScaledInstance(220, 150, Image.SCALE_DEFAULT));
        lbHinhanh.setIcon(icon);
    }

    private void loadCbCart(JComboBox<String> cbMagiohang) {
        new PhieuGiaoHangBLL().loadCbCartId(cbMagiohang);
    }

    private void loadCbCustomer(JComboBox<String> cbMakhachhang) {
        new PhieuGiaoHangBLL().loadCbCustomerId(cbMakhachhang);
    }

    private void loadCbProduct(JComboBox<String> cbMasanpham) {
        new PhieuGiaoHangBLL().loadCbProductId(cbMasanpham);
    }
}
